# Generated by Django 4.0.6 on 2022-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
