# Generated by Django 4.0.6 on 2022-07-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0006_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
