# Generated by Django 4.0.6 on 2022-07-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0008_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pic/default.jpg', upload_to='profile_pic/'),
        ),
    ]
