# Generated by Django 4.0.6 on 2022-07-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
