# Generated by Django 4.0.6 on 2022-08-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='post_id',
            new_name='follower',
        ),
    ]
